const {createClient}=require('@libsql/client');
const TABLES=['animales','hatos','reproduccion','pesajes','produccion','sanidad','potreros','alimentacion','maquinaria','medicamentos','inventario','compras','ventas','clientes','proveedores','finanzas','movimientos','documentos'];
const META=['auditoria','backups'];
const SCHEMA=['CREATE TABLE IF NOT EXISTS config (key TEXT PRIMARY KEY, value TEXT)','CREATE TABLE IF NOT EXISTS tags (id INTEGER PRIMARY KEY AUTOINCREMENT, tag_key TEXT NOT NULL, value TEXT NOT NULL)',...TABLES.map(t=>'CREATE TABLE IF NOT EXISTS '+t+' (id TEXT PRIMARY KEY, data TEXT NOT NULL)'),'CREATE TABLE IF NOT EXISTS auditoria (id INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT NOT NULL)','CREATE TABLE IF NOT EXISTS documentos (id TEXT PRIMARY KEY, data TEXT NOT NULL)','CREATE TABLE IF NOT EXISTS backups (id INTEGER PRIMARY KEY AUTOINCREMENT, data TEXT NOT NULL)'];
class GanaderoDB{
 constructor(){const url=process.env.TURSO_DATABASE_URL,authToken=process.env.TURSO_AUTH_TOKEN;if(!url||!authToken)throw new Error('Faltan TURSO_DATABASE_URL y/o TURSO_AUTH_TOKEN.');this.client=createClient({url,authToken});}
 async init(){await this.client.batch(SCHEMA,'write');await this.client.execute('CREATE INDEX IF NOT EXISTS idx_tags_key ON tags(tag_key)');}
 async loadAll(){const results=await this.client.batch([...TABLES.map(t=>({sql:'SELECT id,data FROM '+t})),{sql:'SELECT id,data FROM auditoria ORDER BY id DESC'},{sql:'SELECT id,data FROM backups ORDER BY id DESC'},{sql:'SELECT tag_key,value FROM tags'},{sql:'SELECT key,value FROM config'}]);const data={};TABLES.forEach((t,i)=>data[t]=results[i].rows.map(r=>JSON.parse(r.data)));data.auditoria=results[TABLES.length].rows.map(r=>JSON.parse(r.data));data.backups=results[TABLES.length+1].rows.map(r=>JSON.parse(r.data));data.tags={};results[TABLES.length+2].rows.forEach(r=>(data.tags[r.tag_key]??=[]).push(r.value));data.config={};results[TABLES.length+3].rows.forEach(r=>{try{data.config[r.key]=JSON.parse(r.value)}catch{data.config[r.key]=r.value}});return data;}
 async saveAll(data){for(const table of TABLES){const incoming=Array.isArray(data[table])?data[table]:[],existing=await this.client.execute('SELECT id FROM '+table),ids=new Set(incoming.map(x=>String(x.id||x.codigo)).filter(Boolean)),statements=[];for(const row of existing.rows)if(!ids.has(String(row.id)))statements.push({sql:'DELETE FROM '+table+' WHERE id=?',args:[row.id]});for(const item of incoming){const id=String(item.id||item.codigo||Date.now()+'-'+Math.random().toString(36).slice(2));statements.push({sql:'INSERT OR REPLACE INTO '+table+'(id,data) VALUES(?,?)',args:[id,JSON.stringify({...item,id})]});}if(statements.length)await this.client.batch(statements,'write');}
 const statements=['DELETE FROM auditoria','DELETE FROM backups','DELETE FROM tags','DELETE FROM config'];for(const a of data.auditoria||[])statements.push({sql:'INSERT INTO auditoria(data) VALUES(?)',args:[JSON.stringify(a)]});for(const b of data.backups||[])statements.push({sql:'INSERT INTO backups(data) VALUES(?)',args:[JSON.stringify(b)]});for(const [k,vals] of Object.entries(data.tags||{}))for(const v of vals||[])statements.push({sql:'INSERT INTO tags(tag_key,value) VALUES(?,?)',args:[k,v]});for(const [k,v] of Object.entries(data.config||{}))statements.push({sql:'INSERT OR REPLACE INTO config(key,value) VALUES(?,?)',args:[k,JSON.stringify(v)]});await this.client.batch(statements,'write');}
 async resetAll(){await this.client.batch([...TABLES,...META,'tags','config'].map(t=>'DELETE FROM '+t),'write');}
 async close(){this.client.close();}
}
module.exports=GanaderoDB;
